
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENQUE = 12;
  public static final int RSTRING = 25;
  public static final int RDECLARA = 23;
  public static final int POR = 10;
  public static final int RWHILE = 30;
  public static final int ENTERO = 18;
  public static final int RVOID = 33;
  public static final int LLAVIZQ = 6;
  public static final int RELSE = 29;
  public static final int IDENTIFICADOR = 27;
  public static final int RPRINT = 22;
  public static final int IGUALQUE = 17;
  public static final int IGUAL = 26;
  public static final int DIVIDIDO = 11;
  public static final int MAYIGUALQUE = 15;
  public static final int UMENOS = 21;
  public static final int EOF = 0;
  public static final int PARIZQ = 4;
  public static final int DECIMAL = 19;
  public static final int MENIGUALQUE = 14;
  public static final int error = 1;
  public static final int COMA = 2;
  public static final int CADENA = 20;
  public static final int MENOS = 9;
  public static final int MAYQUE = 13;
  public static final int LLAVDER = 7;
  public static final int RRETURN = 34;
  public static final int RNUMBER = 24;
  public static final int PTCOMA = 3;
  public static final int PARDER = 5;
  public static final int RFOR = 31;
  public static final int RBREAK = 35;
  public static final int RIF = 28;
  public static final int RFUNCTION = 32;
  public static final int DIFQUE = 16;
  public static final int MAS = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "COMA",
  "PTCOMA",
  "PARIZQ",
  "PARDER",
  "LLAVIZQ",
  "LLAVDER",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "MENQUE",
  "MAYQUE",
  "MENIGUALQUE",
  "MAYIGUALQUE",
  "DIFQUE",
  "IGUALQUE",
  "ENTERO",
  "DECIMAL",
  "CADENA",
  "UMENOS",
  "RPRINT",
  "RDECLARA",
  "RNUMBER",
  "RSTRING",
  "IGUAL",
  "IDENTIFICADOR",
  "RIF",
  "RELSE",
  "RWHILE",
  "RFOR",
  "RFUNCTION",
  "RVOID",
  "RRETURN",
  "RBREAK"
  };
}

